### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by ghost** [step-up-labs/firebase-storage-dotnet#16] opened 2018-06-01 08:45 UTC
This is not an issue but rather an enhancement suggestion. First of thank you Step-up-labs for the API it's really helpful to a lot of C# developers.
I would like to suggest a log in or sign up enhancement using the Firebase SMS authentication. This will be really helpful as it's not currently supported unless you go native especially for Xamarin Forms developers. 
Thank you.

**Comment by bezysoftware** [comment] 2018-06-01 09:03
Duplicate of https://github.com/step-up-labs/firebase-authentication-dotnet/issues/58

**Closed as completed by bezysoftware** 2018-06-01 09:03 UTC
